services:
  pg:
    image: postgres:16
    container_name: client-pg
    environment:
      POSTGRES_USER: client
      POSTGRES_PASSWORD: client
      POSTGRES_DB: clientdb
    ports:
      - "5461:5432"
    volumes:
      - /mnt/c/Users/Pavel/IdeaProjects/HM_project/client-processing/pg-init:/docker-entrypoint-initdb.d:ro

  zookeeper_t1:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper_t1
    container_name: zookeeper_t1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    hostname: broker_t1
    container_name: broker_t1
    depends_on:
      - zookeeper_t1
    ports:
      - "29091:29091"
      - "9091:9091"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_t1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://broker_t1:29091,
        PLAINTEXT_HOST://localhost:9091,
        PLAINTEXT_DOCKER://host.docker.internal:9092
      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:29091,
        PLAINTEXT_HOST://0.0.0.0:9091,
        PLAINTEXT_DOCKER://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker_t1:29091