spring:
  profiles.active: postgres
server.port: 8081
---
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5461/clientdb
    username: client
    password: client
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: client
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: client
    baseline-on-migrate: true
    validate-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9091
    consumer:
      group-id: client-processing
      properties:
        spring.json.trusted.packages: "*"
    properties:
      spring.json.add.type.headers: true
topics:
  client-products: client_products
  client-cards: client_cards
  client-credit-products: client_credit_products
  service-logs: service_logs

app:
  name: client-processing
  metric:
    threshold-ms: 250
  cache:
    ttl-ms: 60000