spring:
  profiles.active: postgres
server.port: 8081
---
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5461/clientdb
    username: client
    password: client
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: client
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: client
    baseline-on-migrate: true
    validate-on-migrate: true
