spring:
  profiles.active: postgres
server.port: 8081
---
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5461/clientdb
    username: client
    password: client
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: client
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: client
    baseline-on-migrate: true
    validate-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9091
    consumer:
      group-id: client-processing
      properties:
        spring.json.trusted.packages: "*"
    properties:
      spring.json.add.type.headers: true

aspects:
  enabled: true

  kafka:
    enabled: true
    topic: service_logs

  http:
     inbound-enabled: true
     outbound-enabled: true

  metric:
     enabled: true
     slow-threshold-ms: 200

  cache:
     enabled: true
     ttl: 5m


topics:
  client-products: client_products
  client-cards: client_cards
  client-credit-products: client_credit_products

app:
  name: client-processing
  metric:
    threshold-ms: 250
  cache:
    ttl-ms: 60000

security:
  jwt:
    issuer: bank-suite
    secret: ${JWT_SECRET:change-me-super-secret-256bit-change-this}
    ttl-sec: 3600
    service-ttl-sec: 120
    service-id: ${SERVICE_ID:${spring.application.name}}

debug: true
logging:
  level:
    com.ms.aspects: DEBUG
    org.springframework.kafka: INFO
