spring:
  profiles.active: postgres
server:
  port: 8083
---
spring:
  config.activate.on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5462/creditdb
    username: credit
    password: credit
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: credit
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: credit
    schemas: credit
    baseline-on-migrate: true
    validate-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9091
    consumer:
      group-id: credit-processing

topics:
  client-credit-products: client_credit_products
  service-logs: service_logs

credit:
  decision:
    limit: 5000000        # лимит N (сумма A+B+C) для отказа/одобрения
  defaults:
    annualRate: 0.22      # ставка по умолчанию (если не придёт откуда-то ещё)
    monthCount: 60        # месяцев по умолчанию
    amount: 1500000       # сумма кредита по умолчанию (для демо)
  mc1:
    base-url: http://localhost:8081
app:
  name: credit-processing
  metric:
    threshold-ms: 250
  cache:
    ttl-ms: 60000